/**
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href=\"https://kinopoiskapiunofficial.tech\">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@kinopoiskapiunofficial.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.gorodechnyj.moviedb.network.api.dto

/**
 *
 * @param type
 * @param subType
 * @param date
 * @param reRelease
 * @param country
 * @param companies
 */
data class Distribution(

    val type: Distribution.Type,
    val subType: Distribution.SubType,
    val date: kotlin.String,
    val reRelease: kotlin.Boolean,
    val country: AllOfDistributionCountry,
    val companies: kotlin.Array<Company>
) {
    /**
     *
     * Values: LOCAL,COUNTRYSPECIFIC,PREMIERE,ALL,WORLDPREMIER
     */
    enum class Type(val value: kotlin.String) {
        LOCAL("LOCAL"),
        COUNTRYSPECIFIC("COUNTRY_SPECIFIC"),
        PREMIERE("PREMIERE"),
        ALL("ALL"),
        WORLDPREMIER("WORLD_PREMIER");
    }

    /**
     *
     * Values: CINEMA,DVD,DIGITAL,BLURAY
     */
    enum class SubType(val value: kotlin.String?) {
        CINEMA("CINEMA"),
        DVD("DVD"),
        DIGITAL("DIGITAL"),
        BLURAY("BLURAY");
    }
}
