/**
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href=\"https://kinopoiskapiunofficial.tech\">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@kinopoiskapiunofficial.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.gorodechnyj.moviedb.network.api.dto

/**
 *
 * @param personId
 * @param webUrl
 * @param nameRu
 * @param nameEn
 * @param sex
 * @param posterUrl
 * @param growth
 * @param birthday
 * @param death
 * @param age
 * @param birthplace
 * @param deathplace
 * @param hasAwards
 * @param profession
 * @param facts
 * @param spouses
 * @param films
 */
data class PersonResponse(

    val personId: kotlin.Int,
    val webUrl: kotlin.String,
    val nameRu: kotlin.String,
    val nameEn: kotlin.String,
    val sex: PersonResponse.Sex,
    val posterUrl: kotlin.String,
    val growth: kotlin.String,
    val birthday: kotlin.String,
    val death: kotlin.String,
    val age: kotlin.Int,
    val birthplace: kotlin.String,
    val deathplace: kotlin.String,
    val hasAwards: kotlin.Int,
    val profession: kotlin.String,
    val facts: kotlin.Array<kotlin.String>,
    val spouses: kotlin.Array<PersonResponseSpouses>,
    val films: kotlin.Array<PersonResponseFilms>
) {
    /**
     *
     * Values: MALE,FEMALE
     */
    enum class Sex(val value: kotlin.String?) {
        MALE("MALE"),
        FEMALE("FEMALE");
    }
}
