/**
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href=\"https://kinopoiskapiunofficial.tech\">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@kinopoiskapiunofficial.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.gorodechnyj.moviedb.network.api.dto

/**
 *
 * @param filmId
 * @param nameRu
 * @param nameEn
 * @param rating
 * @param general
 * @param description
 * @param professionKey
 */
data class PersonResponseFilms(

    val filmId: kotlin.Int? = null,
    val nameRu: kotlin.String? = null,
    val nameEn: kotlin.String? = null,
    val rating: kotlin.String? = null,
    val general: kotlin.Boolean? = null,
    val description: kotlin.String? = null,
    val professionKey: PersonResponseFilms.ProfessionKey? = null
) {
    /**
     *
     * Values: WRITER,OPERATOR,EDITOR,COMPOSER,PRODUCERUSSR,HIMSELF,HERSELF,HRONOTITRMALE,HRONOTITRFEMALE,TRANSLATOR,DIRECTOR,DESIGN,PRODUCER,ACTOR,VOICEDIRECTOR,UNKNOWN
     */
    enum class ProfessionKey(val value: kotlin.String) {
        WRITER("WRITER"),
        OPERATOR("OPERATOR"),
        EDITOR("EDITOR"),
        COMPOSER("COMPOSER"),
        PRODUCERUSSR("PRODUCER_USSR"),
        HIMSELF("HIMSELF"),
        HERSELF("HERSELF"),
        HRONOTITRMALE("HRONO_TITR_MALE"),
        HRONOTITRFEMALE("HRONO_TITR_FEMALE"),
        TRANSLATOR("TRANSLATOR"),
        DIRECTOR("DIRECTOR"),
        DESIGN("DESIGN"),
        PRODUCER("PRODUCER"),
        ACTOR("ACTOR"),
        VOICEDIRECTOR("VOICE_DIRECTOR"),
        UNKNOWN("UNKNOWN");
    }
}
