/**
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href=\"https://kinopoiskapiunofficial.tech\">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@kinopoiskapiunofficial.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.gorodechnyj.moviedb.network.api.dto

/**
 *
 * @param staffId
 * @param nameRu
 * @param nameEn
 * @param description
 * @param posterUrl
 * @param professionText
 * @param professionKey
 */
data class StaffResponse(

    val staffId: kotlin.Int,
    val nameRu: kotlin.String,
    val nameEn: kotlin.String,
    val description: kotlin.String,
    val posterUrl: kotlin.String,
    val professionText: kotlin.String,
    val professionKey: StaffResponse.ProfessionKey
) {
    /**
     *
     * Values: WRITER,OPERATOR,EDITOR,COMPOSER,PRODUCERUSSR,TRANSLATOR,DIRECTOR,DESIGN,PRODUCER,ACTOR,VOICEDIRECTOR,UNKNOWN
     */
    enum class ProfessionKey(val value: kotlin.String) {
        WRITER("WRITER"),
        OPERATOR("OPERATOR"),
        EDITOR("EDITOR"),
        COMPOSER("COMPOSER"),
        PRODUCERUSSR("PRODUCER_USSR"),
        TRANSLATOR("TRANSLATOR"),
        DIRECTOR("DIRECTOR"),
        DESIGN("DESIGN"),
        PRODUCER("PRODUCER"),
        ACTOR("ACTOR"),
        VOICEDIRECTOR("VOICE_DIRECTOR"),
        UNKNOWN("UNKNOWN");
    }
}
